name: retail-data-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - ipykernel>=6.0.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - python-dateutil>=2.8.0
  - pytz>=2023.3
  - pip
  - pip:
    - plotly>=5.0.0
